### ISSUE TITLE
菜单选择模式,能否实现动态加载菜单条目

### ISSUE THREAD

**Issue by bensanpast** [wisdomtl/Selector#1]
您好,看了您的两篇系列文章.深深佩服博主把设计模式灵活运用与Android开发的功力.惊叹于,此组件应对变化的灵活性.联想到如应用于实际开发,可能更多的是通过网络动态加载二级菜单条目.请问老铁,此组件目前支持这样的功能吗.

**Comment by wisdomtl** [comment]
能做到，只需要动态构建Selector实例就可以，并在Selector的子类中定义一个存放数据的字段，通过set()将数据注入
